apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/Greg/Projekte/HumanConnection/graphql/docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
      - env:
        - name: NEO4J_AUTH
          value: none
        image: neo4j:3.4
        name: neo4j
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: neo4j-data
      restartPolicy: Always
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data
status: {}
